{% set version = "3.3.5" %}

package:
    name: fftw
    version: {{ version }}

source:
    fn: fftw-{{ version }}.tar.gz                                             # [not win]
    url: http://www.fftw.org/fftw-{{ version }}.tar.gz                        # [not win]
    sha256: 8ecfe1b04732ec3f5b7d279fdb8efcad536d555f9d1e8fabd027037d45ea8bcf  # [not win]
    fn: fftw-{{ version }}-dll32.zip                               # [win32]
    url: ftp://ftp.fftw.org/pub/fftw/fftw-{{ version }}-dll32.zip  # [win32]
    fn: fftw-{{ version }}-dll64.zip                               # [win64]
    url: ftp://ftp.fftw.org/pub/fftw/fftw-{{ version }}-dll64.zip  # [win64]

build:
    skip: False
    number: 0

requirements:
    build:
        - perl
        - python  # [win]

test:
    requires:
        - python {{ environ['PY_VER'] + '*' }}  # [win]
    commands:
        - exit $(test -f ${PREFIX}/lib/libfftw3f.a)          # [not win]
        - exit $(test -f ${PREFIX}/lib/libfftw3.a)           # [not win]
        - exit $(test -f ${PREFIX}/lib/libfftw3l.a)          # [not win]
        - exit $(test -f ${PREFIX}/lib/libfftw3f_threads.a)  # [not win]
        - exit $(test -f ${PREFIX}/lib/libfftw3_threads.a)   # [not win]
        - exit $(test -f ${PREFIX}/lib/libfftw3l_threads.a)  # [not win]
        
        - if not exist %LIBRARY_INC%\\fftw3.h exit 1         # [win]
          
        {% set baselist = ["libfftw3f-3", "libfftw3-3", "libfftw3l-3"] %}
                  
        {% for base in baselist %}          
        - if not exist %LIBRARY_LIB%\\{{ base }}.lib exit 1  # [win]
        - if not exist %LIBRARY_BIN%\\{{ base }}.dll exit 1  # [win]          
        {% endfor %}


about:
    home: http://fftw.org
    license: GPL 2
    summary: "The fastest Fourier transform in the west."


extra:
    recipe-maintainers:
        - alexbw
        - jakirkham
        - jjhelmus
        - grlee77
        - jschueller
