appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: Yc0RMJJEFJTz4oSpevbCp79ZhQSJlV6Cg+8iXvuQMfBq4K+RPBpthrQMoV62dgFEgK45poLKvpdOvHu3XjZaJ5eyWLR7v9NirSE0ndNpZfxH+vUbY+Bx1ZgpPIS46r7V13tRbDWtpWa/bUpgaXNzayYi15PrTmJveZvRyq4dlvCjh+BJ22mu7+XmCou7q4HSCMLC26IAHvccX8Co+9UehRaWad4GbpljC5Emgd86vgN3Q6cPp7hqZ7rQR6HgaTm0x+1oQgTVPMNOqYmMWbgQJG/UIe9k2WNQGSdXtNdZoJupktlwO1h15wUhuhw6uYFLixO7LrO8oo9gef9d/j7h+oqdYf2u3fpomtUWf1tTD1TgeBqAH36ut/ASePfI8i+QDWtKs21Rq9CDmEnikYZgKMFB6KtwjQXXCbT9KQX1I+gmc1WTn0LnAnE3Rc/kkotI4onwR3xznr7Uf8kg9LePUP9KbI5s7tdaCfzVsNfh6LfKH5STlJ4LrlLtlBUw+O7GtZ+WRkoWTIISQvjZch/vmyAkfHDNnCnQm52cxiuwmxeyaQGVEIPfl2bRBx5sqE6wWVeDuWItKWeZPjtavnwP5qtldojBHfW5xipd7wlKItnLOLdWIwa3m52b57o+ea9Luxguxq6PWAbEnw6v03VKlasBcfn1uLIfJtqDxIMXWHI=}
